[config]
schemaVersion = "0.0.1"

[package]
namespace = "Trodi"
name = "BloodyShop"
versionNumber = "1.0.1"
description = "Mod to create a store in VRising."
websiteUrl = "https://github.com/oscarpedrero/BloodyShop"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.668.5"
deca-Bloodstone = "0.2.2"
deca-VampireCommandFramework = "0.9.0"
Trodi-BloodyCore = "1.2.4"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""

[publish]
communities = ["v-rising"]
repository = "https://thunderstore.io"
[publish.categories]
v-rising = ["1-0-update", "mods", "server", "client"]